<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta http-equiv="X-UA-Compatible" content="IE=edge" />
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no" />
    <link rel="shortcut icon" href="/dist/vite.svg" />
    <?=$this->headTitle('Vandelay')->setSeparator(' - ')->setAutoEscape(false)?>
    <?=$this->headMeta()?>
    <?=$this->headLink()?>
    <style>
        body { padding-top: 70px; }
        .app { min-height: 100vh; }
        .app-footer { padding-bottom: 1em; }
        .mezzio-green, h2 a, h2 a:hover { color: #009655; }
        .navbar-brand { padding: 0; }
        .navbar-brand img { margin: -.5rem 0; filter: brightness(0) invert(1); }

    </style>
</head>
<body class="app">
<div class="app-content">
    <?= $this->content ?>
</div>
<?=$this->inlineScript();?>
</body>
</html>
