<?php $this->headTitle('Home'); ?>

<div class="row">
    <div class="col">
        <h2>Available applications</h2>
        <table class="table">
            <thead>
            <tr>
                <th scope="col">Id</th>
                <th scope="col">Type</th>
                <th scope="col">Category</th>
                <th scope="col"></th>
            </tr>
            </thead>
            <tbody>
            <?php foreach ($this->response['data'] as $item) : ?>
            <tr>
                <th scope="row"><a href="<?= $this->url('apps-installations', ['appId' => $item['id']]);?>"><?= $item['id']; ?></a></th>
                <td><?= $item['appType']; ?></td>
                <td><?= $item['category']; ?></td>
                <td><a href="<?= $this->url('apps-versions',['appId' => $item['id']]);?>">Versions</a></td>
            </tr>
            <?php endforeach; ?>
            </tbody>
        </table>
    </div>
</div>

