<?php
use Laminas\Form\FormInterface;
/** @var FormInterface $form */
$form = $this->connectForm;
$form->prepare();
$form->get('client_id')->setAttributes([
    'class' => 'form-control',
    'id' => 'client_id',
]);
$form->get('client_secret')->setAttributes([
    'class' => 'form-control',
    'id' => 'client_secret',
]);
$form->get('submit')->setAttributes([
    'class' => 'btn btn-primary',
    'id' => 'submit',
]);
?>
<h2>Connect to Capacity</h2>
<div class="row">
    <div class="col-4">
        <?= $this->form()->openTag($form); ?>
        <div class="mb-3">
            <?= $this->formRow($form->get('client_id')); ?>
            <?= $this->formRow($form->get('client_secret')); ?>
        </div>
        <?= $this->formSubmit($form->get('submit')); ?>
        <?= $this->form()->closeTag(); ?>
    </div>
</div>

