<?php

use App\Form\Enroll;
/** @var Enroll $enrollForm */
$form = $this->enrollForm;
$form->prepare();
$form->get('name')->setAttributes([
    'class' => 'form-control',
    'id' => 'name',
]);
$form->get('acceptT&C')
    ->setAttributes([
    'class' => 'form-check-input',
    'id' => 'name',
    ]);
//    ->setLabelAttribute('class', 'form-check-label');

$form->get('submit')
    ->setAttributes([
    'class' => 'btn btn-primary',
    'id' => 'submit',
    ])
    ->setValue('Enroll');
;
?>
<div class="row">
    <div class="col">
        <h2>Welcome to Vandelay Energy</h2>

        <p>To enroll into the DER Flexibility Program, please enter your name.</p>
    </div>
</div>
<div class="row">
    <div class="col-12 col-md-6">
        <?= $this->form()->openTag($form); ?>
        <div class="mb-3">
            <?= $this->formRow($form->get('name')); ?>
            <div class="form-check my-2">
                <?= $this->formCheckbox($form->get('acceptT&C')); ?>
                <?= $this->formLabel($form->get('acceptT&C')); ?>
            </div>
        </div>
        <?= $this->formHidden($form->get('installationId')); ?>
        <?php //echo $this->formHidden($form->get('csrf')); ?>
        <?= $this->formSubmit($form->get('submit')); ?>
        <?= $this->form()->closeTag(); ?>
    </div>
</div>
