name: Build and publish Docker image

defaults:
  run:
    shell: bash

on:
  workflow_dispatch:

jobs:
  build:
    name: Building Docker Image
    runs-on: [ubuntu-latest]
    steps:
      - uses: actions/checkout@v4
        name: Checking out files
      - uses: php-actions/composer@v6
        with:
          php_version: '8.3'
          php_extensions: curl
      - uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: yarn
          cache-dependency-path: app/yarn.lock
      - name: Install dependencies
        run: yarn install --frozen-lockfile
        working-directory: ./app
      - name: Build application
        run: yarn build
        working-directory: ./app
        
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
      
      - name: Log in to GitHub Container Registry
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build and push Docker image
        uses: docker/build-push-action@v5
        with:
          context: .
          push: true
          tags: ghcr.io/${{ github.repository }}:latest

