name: Build and publish Docker image

defaults:
  run:
    shell: bash

on:
  workflow_dispatch:

jobs:
  build:
    name: Install dependencies
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: php-actions/composer@v6
        with:
          php_version: '8.3'
          php_extensions: curl
