name: Continuous Integration Server
on:
  pull_request:
    paths-ignore:
      - 'app/**'
      - '.github/workflows/continuous-integration-app.yml'
      - '.github/workflows/build_publish.yml'
  push:
    paths-ignore:
      - 'app/**'
      - '.github/workflows/continuous-integration-app.yml'
      - '.github/workflows/build_publish.yml'

jobs:
  ci:
    uses: laminas/workflow-continuous-integration/.github/workflows/continuous-integration.yml@1.x
