name: Continuous Integration
on:
  pull_request:
    paths-ignore:
      - 'app/**'
  push:
    paths-ignore:
      - 'app/**'

jobs:
  ci:
    uses: laminas/workflow-continuous-integration/.github/workflows/continuous-integration.yml@1.x
